import { demoInfo } from "./demo.js";
import { agentsScene, agentsSetupScene } from "./agents-demo.js";
import { agents, assistant, info, note, startup, submit, tool, turnDone, type } from "./steps.js";

export const agentsPages = [
  {
    id: "agents.create", feature: "← Agents", title: "Create a Team",
    steps: [
      note(["Create a team through the Agents interface, starting from an empty chat prompt.", "Watch Left, n, the name form and the first-member picker. No commands run in this demo."]),
      startup(demoInfo({ session: "demo-team" })),
      agents(agentsSetupScene("empty-navigation"), "Press Left from an empty prompt. Inbox shows decisions and deliveries; Manager and Independent are in the navigation."),
      agents(agentsSetupScene("new-team"), "Press n for New team. Type product in Team name, then Enter. Esc cancels the form."),
      agents(agentsSetupScene("first-member-menu"), "The team is created and Add member opens automatically. Select Existing folder with ↑↓ and Enter."),
      agents(agentsSetupScene("first-member-folder"), "Enter ~/demo in Folder. Tab completes paths; Enter advances through Name and the optional role fields, then saves."),
      agents(agentsScene("created"), "demo is now the leader. Organization shows the member tree; Tab switches to Tasks. Enter on a member opens its conversations."),
      note(["The team registry lives in your RIND_HOME. Adding a folder does not move its files."]),
      agents({ ...agentsScene("created"), focus: "sidebar" }, "Esc from the main list goes back to the sidebar. Esc again returns to the conversation you left."),
      agents(null, "Back in your original chat. The demo changed only its simulated management page, not any real team, folder or conversation."),
      note(["Try it after leaving the tour: Left, n, name your team, then pick its first folder.", "Tour keys control playback; they do not submit the simulated forms."]),
    ],
  },
  {
    id: "agents.add", feature: "Any folder", title: "Add a specialist",
    steps: [
      note(["A specialist keeps its own workspace, project skills and files. Position and responsibility are optional."]),
      startup({ ...demoInfo({ session: "demo-team" }), management_label: "Team: product" }),
      agents(agentsScene("created"), "Press Left, open product, select demo, then press a to add a member below the leader."),
      agents(agentsSetupScene("add-menu"), "Choose Existing folder. You can also create a fresh workspace or a Git worktree from this same menu."),
      agents(agentsSetupScene("specialist-folder"), "Type ~/finance in Folder. Enter advances to Name; the folder name is suggested. Existing files and skills stay in place."),
      agents(agentsSetupScene("specialist-role"), "Role is optional. Type Finance; it appears next to the member in the organization tree. Enter advances to Responsibility."),
      agents(agentsSetupScene("specialist-responsibility"), "Type Reconcile invoices in Responsibility. It becomes part of this member's team-task instructions. Enter saves."),
      agents(agentsSetupScene("share-folder"), "If the folder belongs to another team, this choice appears. Make an independent copy is recommended; Cancel leaves both teams unchanged."),
      agents(agentsSetupScene("share-confirm"), "For this example, explicitly share the folder: select Share this folder and confirm with Enter. The same files are used by both teams."),
      note(["Shared folders run one task at a time; each team's conversations and reports remain separate."]),
      agents(agentsSetupScene("specialist"), "finance now appears below demo. Press e to edit its role later, or c to start a direct conversation with the selected member."),
      info({ ...demoInfo({ cwd: "~/finance", session: "demo-finance" }), management_label: "Team: product" }, true),
      agents(null, "The demo pressed c. This previews the finance member's chat. Left from an empty prompt reopens Agents."),
      note(["You can talk to any member directly. The team observes activity without broadcasting this private conversation."]),
    ],
  },
  {
    id: "agents.worktree", feature: "Worktrees", title: "Parallel features",
    steps: [
      note(["Different feature worktrees have different directories, so they can run in parallel."]),
      startup({ ...demoInfo({ session: "demo-team" }), management_label: "Team: product" }),
      agents(agentsScene("created"), "Press Left and open product. Select demo, then press a to add a member below it."),
      agents(agentsSetupScene("worktree-menu"), "Select New Git worktree with ↑↓, then press Enter. This creates a member on a separate Git branch."),
      agents(agentsSetupScene("worktree-repository"), "Start with Repository: ~/demo. Tab completes folder names. The selected folder must be a Git repository."),
      agents(agentsSetupScene("worktree-branch"), "Enter feature/search in New branch. The branch must not exist yet. Enter advances to the new folder name."),
      agents(agentsSetupScene("worktree-folder"), "Folder name defaults from the branch: feature-search. It will live inside the team's workspace area."),
      agents(agentsSetupScene("worktree-base"), "Start from is HEAD by default. Choose a branch, tag or commit, then fill the optional role fields and Enter to save."),
      agents(agentsSetupScene("search"), "feature-search is registered as a member. Its files live in ~/demo/worktrees/feature-search, on branch feature/search."),
      agents(agentsSetupScene("export-branch"), "Repeat a → New Git worktree for feature/export. The demo fills a second worktree form, starting from the same repository."),
      agents(agentsSetupScene("worktrees"), "Both worktree members now appear in Organization. Their different directories allow independent work on search and export."),
      note(["The leader can create workspaces and worktrees within the team's creation root too.", "Only members registered in the current team can receive team tasks."]),
    ],
  },
  {
    id: "agents.tasks", feature: "Tasks & reports", title: "Assign and review work",
    steps: [
      note(["A Task is tracked work: an assignee, status and delivery report.", "Assign one to the leader from Agents; it can delegate child tasks and integrate their reports."]),
      startup({ ...demoInfo({ session: "demo-team" }), management_label: "Team: product" }),
      agents(agentsScene(), "Press Left, open product, select the leader and press t to assign a task. Enter the brief, then confirm the form."),
      agents(agentsScene("assign"), "Give the task an outcome and expected evidence. Enter saves; Esc cancels. This filled form is only a simulation."),
      agents(agentsScene("queued"), "The task is queued. A managed task runs in its own conversation; your original chat stays separate."),
      agents(agentsScene("delegated"), "The leader used agent_management assignTask and ended its turn. Its parent task is Delegated while the reviewer works."),
      note(["The scheduler waits after the parent's turn ends, then resumes it on child delivery.", "It does not force the model to stop: a running turn may still sleep or poll. Ordinary chat is different."]),
      agents(agentsScene("resumed"), "The reviewer delivered a report. The scheduler resumes the parent task in the same managed conversation, in a new run."),
      agents(agentsScene("delivered"), "The leader integrated the result and delivered. Tab opens Tasks; Enter on Done opens its report."),
      agents(agentsScene("report"), "Review the summary, evidence and files. Accept the delivery or request rework with feedback from the task's actions."),
      agents({ ...agentsScene("report"), reportOffset: 8 }, "In a real report, ↑↓ scrolls to evidence and files. The demo scrolled down; no file is created or opened."),
      note(["Task delivery needs a report, not just a finished process. Needs input asks for a decision.", "Unconfirmed: the old process cannot be verified. Check it stopped before retrying."]),
    ],
  },
  {
    id: "agents.sessions", feature: "Task / session", title: "Direct chat and tasks",
    steps: [
      note(["A Session is conversation history; a Task is a tracked work item.", "One member can have many sessions. Direct chat does not automatically create a task for the member."]),
      startup({ ...demoInfo({ session: "demo-team" }), management_label: "Team: product" }),
      agents(agentsScene(), "Press Left and open product. Enter on demo opens this member's conversation list; c starts a new direct conversation."),
      agents(agentsSetupScene("leader-sessions"), "Select A direct conversation and press Enter to join it. This is conversation history, not a managed parent task."),
      info({ session_id: "demo-direct" }, true),
      agents(null, "The demo joined the selected conversation. Ask the member to assign work, just as you would in ordinary chat."),
      type("Ask reviewer to inspect Unicode handling and deliver a report."), submit(),
      tool("agent_management", "assignTask", { status: "ok", output: "Reviewer task queued. No parent task: this is direct chat.", durationMs: 120 },
        { action: "assignTask", parameters: { teamId: "product", assigneeAgentId: "reviewer", brief: "Inspect Unicode handling" } }),
      assistant("The reviewer has a tracked task. This conversation is still direct chat; open Agents to follow its delivery."),
      turnDone(2500, 1, 0),
      agents(agentsScene("direct"), "Only the assigned reviewer task appears in Tasks. The direct leader conversation has no parent task."),
      note(["Child completion does not automatically resume an ordinary direct chat. Use a managed parent task for that workflow.", "A task's session can span several runs; its report tracks delivery."]),
    ],
  },
];
