import { demoInfo, SKILLS } from "./demo.js";
import { assistant, note, shell, slashResult, startup, submit, tool, turnDone, turnStart, type } from "./steps.js";

export const configPages = [
  {
    id: "config.init",
    title: "Project docs & skills",
    steps: [
      note([
        "RIND.md is the project's standing instructions — Rind drafts it from",
        "your codebase and injects it into context every turn.",
      ]),
      shell("rind"),
      startup(demoInfo({ session: "20260917_101530_ab12cd34" })),
      type("/init"),
      submit(),
      slashResult({ text: "Initializing project RIND.md: ~/demo/RIND.md" }),
      turnStart("Initialize project RIND.md at ~/demo/RIND.md"),
      tool("read_file", "README.md", { status: "ok", output: "Parser demo. Run npm test to check changes.", durationMs: 120 }),
      tool("edit_file", "RIND.md", { status: "ok", output: "drafted project doc", durationMs: 600 }),
      assistant("Drafted RIND.md with the project overview and test command. Please review it before your next task."),
      turnDone(3800, 2, 0),
      type("/skill list"),
      submit(),
      slashResult({
        text: "Skills",
        display: {
          type: "skills",
          skills: SKILLS,
        },
      }),
      note([
        "Skills come from .rind/skills (project) and ~/.rind/skills (user).",
        "Try /skill list, then mention an installed skill in your next prompt. Review the RIND.md generated by /init before relying on it.",
      ]),
    ],
  },
];
