import { demoInfo, SKILLS } from "./demo.js";
import { assistant, note, shell, shellOut, slashResult, startup, submit, tool, turnDone, turnStart, type } from "./steps.js";

export const configPages = [
  {
    id: "config.init",
    feature: "/init /skill",
    title: "Project docs & skills",
    steps: [
      note([
        "RIND.md is the project's standing instructions — Rind drafts it from",
        "your codebase and injects it into context every turn.",
      ]),
      shell("rind"),
      startup(demoInfo({ session: "20260917_101530_ab12cd34" })),
      type("/init"),
      submit(),
      slashResult({ text: "Initializing project RIND.md: ~/demo/RIND.md" }),
      turnStart("Initialize project RIND.md at ~/demo/RIND.md"),
      tool("read_file", "README.md", { status: "ok", output: "Parser demo. Run npm test to check changes.", durationMs: 120 }),
      tool("edit_file", "RIND.md", { status: "ok", output: "drafted project doc", durationMs: 600 }),
      assistant("Drafted RIND.md with the project overview and test command. Please review it before your next task."),
      turnDone(3800, 2, 0),
      type("/skill list"),
      submit(),
      slashResult({
        text: "Skills",
        display: {
          type: "skills",
          skills: SKILLS,
        },
      }),
      note([
        "Skills come from .rind/skills (project) and ~/.rind/skills (user).",
        "Try /skill list, then mention an installed skill in your next prompt. Review the RIND.md generated by /init before relying on it.",
      ]),
    ],
  },
  {
    id: "config.folder", feature: "Folder defaults", title: "Per-project selection",
    steps: [
      note(["Give each project its own connection, model and effort defaults.", "New conversations and managed agent tasks use them; existing sessions keep their saved selection."]),
      shell("rind config set model glm-4.7 --connection zai --folder"),
      shellOut(["New conversations in ~/demo start with:", "  model   zai / glm-4.7  (this folder)", "  effort  high  (settings.json)"]),
      shell("rind config set effort high --folder"),
      shellOut(["New conversations in ~/demo start with:", "  model   zai / glm-4.7  (this folder)", "  effort  high  (this folder)"]),
      note(["Folder defaults live in RIND_HOME/workspaces.json, not project settings. Worktrees inherit the main repository unless overridden.", "Keys stay in auth.json. --folder alone means the current directory."]),
      shell("rind config unset model --folder"),
      shell("rind config unset effort --folder"),
      note(["Unset removes the folder override so the normal fallback applies again. This tour does not write any settings."]),
    ],
  },
];
